improve(kong) addressing real use feedbacks

diff --git a/templates/kong_init.sh.j2 b/templates/kong_init.sh.j2
--- a/templates/kong_init.sh.j2
+++ b/templates/kong_init.sh.j2
@@ -1,20 +1,10 @@
 #!/bin/sh
 set -e
 
-# Disabling nginx daemon mode
+# Disabling nginx daemon mode, in case if there was override in main config
 export KONG_NGINX_DAEMON="off"
 
-# Setting default prefix (override any existing variable)
-export KONG_PREFIX="/usr/local/kong"
-
-# Prepare Kong prefix
-
-if [ ! -d /usr/local/kong/ ];then
-  if [ "$1" = "/usr/local/openresty/nginx/sbin/nginx" ]; then
-  	kong prepare -p "/usr/local/kong"
-  fi
-fi
-
-kong migrations up || true
+# Those will fail for case when db is already migrated
+/usr/local/bin/kong migrations up  || true
 
 exec "$@"
